import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import ClientSideScrollRestorer from "@/src/ClientSideScrollRestorer";

export const metadata: Metadata = {
  title: "Api App Image",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <ClientSideScrollRestorer />
        </Providers>
      </body>
    </html>
  );
}
